Sys.setlocale("LC_TIME", "English")
source("source/[B] Figures ENG/[PieCharts] TSI.R", encoding = "UTF-8")
source("source/[B] Figures ENG/[TimeSeries] conc comparison.R", encoding = "UTF-8")
source("source/[B] Figures ENG/[TimeSeries] load comparison.R", encoding = "UTF-8")
source("source/[B] Figures ENG/[TimeSeries] grid.R", encoding = "UTF-8")
source("source/[B] Figures ENG/[TimeSeries] flow.R", encoding = "UTF-8")
source("source/[B] Figures ENG/[TimeSeries] volumes and areas.R", encoding = "UTF-8")
