
delft1_B12<- read.csv2("dataset/setores/Setor1_B12_Delft.csv") %>% mutate(Setor="Setor 1", Cenario="B12", model="Delft3D")
delft1_A35<- read.csv2("dataset/setores/Setor1_A35_Delft.csv") %>% mutate(Setor="Setor 1", Cenario="A35", model="Delft3D")
delft2_B12<- read.csv2("dataset/setores/Setor2_B12_Delft.csv") %>% mutate(Setor="Setor 2", Cenario="B12", model="Delft3D")
delft2_A35<- read.csv2("dataset/setores/Setor2_A35_Delft.csv") %>% mutate(Setor="Setor 2", Cenario="A35", model="Delft3D")
delft3_B12<- read.csv2("dataset/setores/Setor3_B12_Delft.csv") %>% mutate(Setor="Setor 3", Cenario="B12", model="Delft3D")
delft3_A35<- read.csv2("dataset/setores/Setor3_A35_Delft.csv") %>% mutate(Setor="Setor 3", Cenario="A35", model="Delft3D")
delft4_B12<- read.csv2("dataset/setores/Setor4_B12_Delft.csv") %>% mutate(Setor="Setor 4", Cenario="B12", model="Delft3D")
delft4_A35<- read.csv2("dataset/setores/Setor4_A35_Delft.csv") %>% mutate(Setor="Setor 4", Cenario="A35", model="Delft3D")
delft<-rbind(delft1_B12,delft1_A35,delft2_B12,delft2_A35,delft3_B12,delft3_A35,delft4_B12,delft4_A35)
delft$Data <- as.Date(delft$Data,format="%d/%m/%Y" )
